name: hiking_tracker
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^12.0.0
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  intl: ^0.19.0
  uuid: ^4.4.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true